config/routes.rb
Rails.application.routes.draw do
  get 'questions/show'
  get 'questions/answer'
  get 'grades/show'
  get 'grades/summary'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#show'

  namespace :admin do
    resources :grades do
      resources :questions
    end
  end

  resources :grades, only: [:show] do
    member do
      get :summary
      post :start
    end
    resources :questions, only: [:show] do
      member do
        post :answer
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord

  has_many :questions, dependent: :restrict_with_exception
  validates :title, presence: true

  scope :published, ->{ where(published: true)}

end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :grade

  validates :sentence, presence: true

end

app/controllers/admin/grades_controller.rb
class Admin::GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to [:admin, @grade], notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @grade] }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to [:admin, @grade], notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @grade] }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to admin_grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:title, :published, :grade_num)
    end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :set_grade
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = @grade.questions.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.grade = @grade

    respond_to do |format|
      if @question.save
        format.html { redirect_to [:admin, @grade, @question], notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @grade, @question] }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to [:admin, @grade, @question], notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @grade, @question] }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_grade_questions_url(@grade), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_grade
      @grade = Grade.find(params[:grade_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:sentence, :answer, :published)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade

  def show
  end

  def start
    session['a'] = @grade.question_ids.map.with_index(1) do |id, i|
      {'num' => i, 'qid' => id, 'ok' => nil, 'a' => nil}
    end
    redirect_to grade_question_path(@grade, session['a'].first['qid'])
  end

  def summary
    @answers = session['a']
    @result = @answers.select{|a| a['ok'] == true}.size.to_f / @answers.size
  end

  private
    def set_grade
      @grade = Grade.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @grades = Grade.published
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_grade
  before_action :set_question

  def show
    @answer = session['a'].detect{|answer| answer['qid'] == @question.id}
  end

  def answer
    @answer = session['a'].detect{|answer| answer['qid'] == @question.id}
    @answer['a'] = params['a']
    @answer['ok'] = (params['a'] == @question.answer)
    @next_answer = session['a'].detect{|answer| answer['num'] == @answer['num'] + 1}
  end

  private
    def set_grade
      @grade = Grade.find(params[:grade_id])
    end

    def set_question
      @question = Question.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/grades/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admin, @grade]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :published
    = f.input :grade_num

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/admin/grades/edit.html.haml
%h1 Editing grade

= render 'form'

= link_to 'Show', [:admin, @grade]
\|
= link_to 'Back', admin_grades_path

app/views/admin/grades/index.html.haml
%h1 Listing grades

%table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th Title
      %th Published
      %th Grade num
      %th
      %th
      %th

  %tbody
    - @grades.each do |grade|
      %tr
        %td= grade.title
        %td= grade.published
        %td= grade.grade_num
        %td= link_to 'Show', [:admin, grade]
        %td= link_to 'Edit', edit_admin_grade_path(grade)
        %td= link_to 'Destroy', [:admin, grade], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Grade', new_admin_grade_path

app/views/admin/grades/new.html.haml
%h1 New grade

= render 'form'

= link_to 'Back', admin_grades_path

app/views/admin/grades/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @grade.title
%p
  %b Published:
  = @grade.published
%p
  %b Grade num:
  = @grade.grade_num

= link_to 'Edit', edit_admin_grade_path(@grade)
\|
= link_to 'Back', admin_grades_path

app/views/admin/questions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admin, @grade, @question]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :sentence
    = f.input :answer
    = f.input :published

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/admin/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', [:admin, @grade, @question]
\|
= link_to 'Back', admin_grade_questions_path(@grade)

app/views/admin/questions/index.html.haml
%h1 Listing questions

%table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th Sentence
      %th Answer
      %th Published
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.sentence
        %td= question.answer
        %td= question.published
        %td= link_to 'Show', [:admin, @grade, question]
        %td= link_to 'Edit', edit_admin_grade_question_path(@grade, question)
        %td= link_to 'Destroy', [:admin, @grade, question], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Question', new_admin_grade_question_path(@grade)

app/views/admin/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', admin_grade_questions_path(@grade)

app/views/admin/questions/show.html.haml
%p#notice= notice

%p
  %b Grade:
  = @question.grade_id
%p
  %b Sentence:
  = @question.sentence
%p
  %b Answer:
  = @question.answer
%p
  %b Published:
  = @question.published

= link_to 'Edit', edit_admin_grade_question_path(@grade, @question)
\|
= link_to 'Back', admin_grade_questions_path(@grade)

app/views/grades/show.html.haml
%div.text-center
  %ol.breadcrumb
    %li= link_to "Home", root_path
    %li.active @grade.title
  .page-header
    %h1
      %small Grade:
      = @grade.title
  .page-body
    %p= "Are you ready? Click below link!"
    %div= link_to("Press N key to start!!! (or click this link)", start_grade_path(@grade), method: :post, id: :start)

%audio#start_sound{preload: "auto"}
  %source{src: "/sounds/start.m4a", type: "audio/mp3"}
  %p ※お使いのブラウザでは音は鳴りません。

:coffee
  $(window).on 'keydown', (event) ->
      k = event.key
      if k == 'n' || k == 'N'
        document.querySelector("#start_sound").play()
        document.querySelector("#start").click()

app/views/grades/summary.html.haml
%div.text-center
  %ol.breadcrumb
    %li= link_to "Home", root_path
    %li= link_to @grade.title, @grade
    %li.active= "Your Score"
  .page-header
    %h1 Your score!!
  .page-body
    %div
      %span= "score: #{(@result*100).to_i}%"

    %h2 Detail

    // %table.table-striped.table-hover.text-center
    %table.table.text-left{style: "width:80%; margin: 0 auto"}
      %thead
        %tr
          %th.text-right{style: "width:10%"} No.
          %th Sentence
          %th{style: "width:15%"} Correct Answer
          %th{style: "width:15%"} Your Answer
          %th{style: "width:10%"} Result

      %tbody
        - @answers.each do |answer|
          %tr
            %td.text-right= answer['num']
            %td= Question.find(answer['qid']).sentence
            %td= Question.find(answer['qid']).answer
            %td= answer['a']
            %td= answer['ok']

    %br

app/views/home/show.html.haml
%h1 Listing grades for being great vimmer!!

%table.table-striped.table-hover
  %thead
    %tr
      %th title

  %tbody
    - @grades.each do |grade|
      %tr
        %td= link_to grade.title, grade

%br

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GreatVimmer
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/questions/answer.html.haml
%div.text-center
  %ol.breadcrumb
    %li= link_to "Home", root_path
    %li= link_to @grade.title, @grade
    %li.active= "Answer No.#{@answer['num']} (Total #{session['a'].size})"
  .page-header
    %h1= "Answer No.#{@answer['num']}"
  .page-body
    %p#result{data: {result: @answer['ok'].to_s}}= (@answer['ok'])? "OK!" : "NG!"
    %p= "your answer: #{@answer['a']}"
    %p= "correct: #{@question.answer}"
    - if @next_answer
      %div= link_to("Press N key to go to next question! (or click this link)", grade_question_path(@grade, @next_answer['qid']), id: :next)
    - else
      %div= link_to("Press N key to see your socre! (or click this link)", summary_grade_path(@grade), id: :next)


%audio#ok{preload: "auto"}
  %source{src: "/sounds/ok.m4a", type: "audio/mp3"}
  %p ※お使いのブラウザでは音は鳴りません。
%audio#ng{preload: "auto"}
  %source{src: "/sounds/ng.m4a", type: "audio/mp3"}
  %p ※お使いのブラウザでは音は鳴りません。

:coffee
  if $("#result").data('result') == true
    document.querySelector("#ok").play()
  else
    document.querySelector("#ng").play()
  $(window).on 'keydown', (event) ->
      k = event.key
      if k == 'n' || k == 'N'
        document.querySelector("#next").click()

app/views/questions/show.html.haml
%div.text-center
  %ol.breadcrumb
    %li= link_to "Home", root_path
    %li= link_to @grade.title, @grade
    %li.active= "Question No.#{@answer['num']} (Total #{session['a'].size})"
  .page-header
    %h1= "Question No.#{@answer['num']}"
  .page-body
    %div
      %p.well.question= @question.sentence
      %p type!
    %div= link_to("answer(kari)", answer_grade_question_path(@grade, @question), method: :post)

= form_with(url: answer_grade_question_path(@grade, @question), local: true, id: :form, data: {max: 1, current: 0}) do |f|
  = ""

:coffee
  $(window).on 'keydown', (event) ->
      c = if event.which then event.which else event.keyCode
      k = event.key
      if c == 16 || c == 91 || c == 18 || c == 20 || c == 13 || c == 17# shift, meta(command/win), alt(option), caps lock, enter, control
        console.log k
        # Shift
        # Alt
        # Meta
        # CapsLock
        # Enter
        return false
      a = '';
      if event.shiftKey
        a = k
      else if event.altKey
        a = "alt+" + k
      else if event.metaKey
        a = "meta+" + k
      else if event.ctrlKey
        a = "ctrl+" + k
      else
        a = k
      console.log a
      $form = $("#form")
      $form.append("<input type='hidden' name='a' value='" + k + "'>")
      $form.data('current', $form.data('current') + 1)
      if $form.data('current') >= $form.data('max')
        console.log('submit')
        $form.submit()

      return false